- name: "Ansible playbook create directory structure"
  hosts: controlmachine
  vars:
    tmp_project_name : temp

  tasks:
   - name: Create project parent dir
     file:
        path: "{{ tmp_project_name }}"
        state: directory  
        
   - name: Create inventory
     include_role:
        name: create-inventory

   - name: Create common dirs
     include_role:
        name: common

   - name: Create roles
     include_role:
        name: create-role

   - name: Move project dir
     command: mv {{ tmp_project_name }} ../{{ project_name }}
  
