- name: "Ansible playbook example"
  hosts: controlmachine
  tasks:
   - name: Create project parent dir
     file:
        path: "{{ project_name }}"
        state: directory        

   - name: Create inventory files
     file:
        path: "{{ project_name }}/{{ item }}"
        state: touch
     loop: "{{ inventory_files }}"  
  ############################################ 
   - name: Create group_vars 
     file:
        path: "{{ project_name }}/group_vars"
        state: directory  
     when: group_vars.create

   - name: Create group_vars files
     file:
        path: "{{ project_name }}/group_vars/{{ item }}"
        state: touch  
     loop: "{{group_vars.files}}"
     when: group_vars.create and group_vars.files|length > 0

   - name: Create host_vars dir
     file:
        path: "{{ project_name }}/host_vars"
        state: directory  
     when: host_vars.create 

   - name: Create host_vars files
     file:
        path: "{{ project_name }}/host_vars/{{ item }}"
        state: touch  
     loop: "{{host_vars.files}}"
     when: host_vars.create and host_vars.files|length > 0

   ############################################ 
   - name: Create module_utils 
     file:
        path: "{{ project_name }}/module_utils"
        state: directory  
     when: module_utils.create

   - name: Create filter_plugins 
     file:
        path: "{{ project_name }}/filter_plugins"
        state: directory  
     when: filter_plugins.create

   - name: Create library 
     file:
        path: "{{ project_name }}/library"
        state: directory  
     when: library.create
    ###############################

  #  - name: Create role dirs
  #    file:
  #       path: "{{ project_name }}/roles/{{ item.name }}"
  #       state: directory       
  #    when: item.create
  #    loop: "{{roles_dir}}"

   - name: Create role dirs
     include_tasks: 
        file: tasks.yml
        apply:
          tags:
           - create_role
     vars: 
       - dir_data : "{{ item }}"  
     when: item.create
     loop: "{{roles_dir}}"
     tags: create_role

  
