#Create dir
- name: Create dir
  file:
    path: "{{ tmp_project_name }}/roles/{{role_dir_name}}/{{ dir_data.name }}"
    state: directory
  when: dir_data is defined  
#Create files if available
- name: Create files
  file:
    path: "{{ tmp_project_name }}/roles/{{role_dir_name}}/{{ dir_data.name }}/{{file_item}}"
    state: touch 
  loop: "{{dir_data.files}}"
  when: dir_data.files is defined and dir_data.files|length > 0
  loop_control:
    loop_var: file_item
