project_name: ansible-sample-project
inventory_files: [production,staging]
group_vars: 
    create: true,
    files : [group1.yml, group2.yml]        # here we assign variables to particular groups
host_vars: 
    create: true,
    files : [group1.yml, group2.yml]        # here we assign variables to particular systems
library: 
    create: true                              # if any custom modules, put them here (optional)
module_utils: 
    create: true                         # if any custom module_utils to support modules, put them here (optional)
filter_plugins: 
    create: true                      # if any custom filter plugins, put them here (optional)
playbooks: 
    create: true
    files: [site.yml ,webservers.yml,dbservers.yml] #play books
role_name: "{{ role | default('defualt') }}"
roles_dir:
                # this hierarchy represents a "role"
        -  name: tasks 
           create: true,
           files: [main.yml]     #  <-- tasks file can include smaller files if warranted
        -  name: handlers 
           create: true,
           files: [main.yml]   #  <-- handlers file
        -  name: templates  
           create: true,
           files: [sample.j2]      #  <-- files for use with the template resource,templates end in .j2
        -  name: files  
           create: true,
           files: [sample.txt,sample.sh]          #           
        -  name: vars 
           create: true,
           files: [main.yml]     #  <-- variables associated with this role
        -  name: defaults 
           create: true,
           files: [main.yml]      #  <-- default lower priority variables for this role
        -  name: meta 
           create: true,
           files: [main.yml]      #  <-- role dependencies
        -  name: library 
           create: true         # roles can also include custom modules
        -  name: module_utils 
           create: true    # roles can also include custom module_utils
        -  name: lookup_plugins 
           create: true  # or other types of plugins, like lookup in this case